import { createClient } from '@/lib/supabase/server';
import { NextResponse } from 'next/server';

function cmsLib(slug: string, origin: string) {
  return `// lib/cms.ts - generated by NE Website Manager

const CMS_BASE = '${origin}';
const CLIENT_SLUG = '${slug}';

export interface CmsPost {
  id: string;
  title: string;
  slug: string;
  content: string;
  excerpt: string;
  cover_url: string | null;
  category: string;
  tags: string[];
  status: 'published';
  seo_title: string | null;
  seo_description: string | null;
  published_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface CmsPage {
  id: string;
  title: string;
  path: string;
  content: string;
  status: 'published';
  visibility: 'public';
  updated_at: string;
}

export type AnalyticsMetadata = Record<string, string | number | boolean | null>;

async function fetchJson<T>(path: string): Promise<T> {
  const res = await fetch(\`\${CMS_BASE}\${path}\`, { next: { revalidate: 60 } });
  if (!res.ok) throw new Error(\`NE Website Manager request failed: \${res.status}\`);
  return res.json() as Promise<T>;
}

function getVisitorId() {
  if (typeof window === 'undefined') return undefined;
  const key = 'ne_visitor_id';
  let id = window.localStorage.getItem(key);
  if (!id) {
    id = crypto.randomUUID?.() ?? Math.random().toString(36).slice(2);
    window.localStorage.setItem(key, id);
  }
  return id;
}

function getSessionId() {
  if (typeof window === 'undefined') return undefined;
  const key = 'ne_session_id';
  let id = window.sessionStorage.getItem(key);
  if (!id) {
    id = crypto.randomUUID?.() ?? Math.random().toString(36).slice(2);
    window.sessionStorage.setItem(key, id);
  }
  return id;
}

export function getPosts(params?: { category?: string; limit?: number }): Promise<CmsPost[]> {
  const search = new URLSearchParams();
  if (params?.category) search.set('category', params.category);
  if (params?.limit) search.set('limit', String(params.limit));
  const qs = search.toString();
  return fetchJson<CmsPost[]>(\`/api/client/\${CLIENT_SLUG}/posts\${qs ? \`?\${qs}\` : ''}\`);
}

export function getPostBySlug(slug: string): Promise<CmsPost | null> {
  return fetchJson<CmsPost>(\`/api/client/\${CLIENT_SLUG}/posts/\${encodeURIComponent(slug)}\`)
    .catch(() => null);
}

export function getPages(): Promise<CmsPage[]> {
  return fetchJson<CmsPage[]>(\`/api/client/\${CLIENT_SLUG}/pages\`);
}

export function trackEvent(eventName: string, metadata: AnalyticsMetadata = {}) {
  if (typeof window === 'undefined') return Promise.resolve();

  const payload = {
    event_name: eventName,
    path: window.location.pathname,
    title: document.title,
    referrer: document.referrer,
    visitor_id: getVisitorId(),
    session_id: getSessionId(),
    metadata,
  };

  return fetch(\`\${CMS_BASE}/api/client/\${CLIENT_SLUG}/analytics\`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    keepalive: true,
    body: JSON.stringify(payload),
  }).then(() => undefined).catch(() => undefined);
}

export function trackPageView(metadata: AnalyticsMetadata = {}) {
  return trackEvent('page_view', metadata);
}

export function installAnalytics() {
  if (typeof window === 'undefined') return;
  trackPageView();

  const originalPushState = history.pushState;
  const originalReplaceState = history.replaceState;
  const emit = () => window.setTimeout(() => trackPageView(), 0);

  history.pushState = function pushState(...args) {
    originalPushState.apply(this, args);
    emit();
  };
  history.replaceState = function replaceState(...args) {
    originalReplaceState.apply(this, args);
    emit();
  };
  window.addEventListener('popstate', emit);
}
`;
}

export async function GET(
  req: Request,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params;
  const supabase = await createClient();

  const { data: client } = await supabase
    .from('clients')
    .select('id')
    .eq('slug', slug)
    .single();

  if (!client) {
    return NextResponse.json({ error: 'Client not found' }, { status: 404 });
  }

  return new Response(cmsLib(slug, new URL(req.url).origin), {
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Content-Type': 'text/plain; charset=utf-8',
    },
  });
}

export async function OPTIONS() {
  return new Response(null, {
    status: 204,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
    },
  });
}
