import { describe, expect, it } from 'vitest';
import { generateV1Sdk, generateV2Sdk, generateV2ServerSdk, toPascalCase, type SdkCollectionInput } from './generate';
import type { FieldDef } from '@/lib/collections/types';

const TEST_SLUG = 'acme';
const TEST_ORIGIN = 'https://cms.example.com';

/**
 * Byte-for-byte fixture of `sdk/route.ts`'s `cmsLib(slug, origin)` output as
 * it existed at commit `2145da5` — the last commit before this task (7.2)
 * touched anything, confirmed via `git show 2145da5:src/app/api/client/
 * [slug]/sdk/route.ts` and a `diff` against the working tree's copy of that
 * file immediately before it was refactored to call `generateV1Sdk` (zero
 * differences). Transcribed here with only the two real interpolation
 * points (`${origin}` -> the literal below, `${slug}` -> the literal below)
 * substituted; every other character — including every escaped backtick and
 * escaped `${...}` that appears literally in the OUTPUT (nested template-
 * literal syntax the generated `lib/cms.ts` itself contains) — is preserved
 * exactly as it appeared in that historical file.
 *
 * This is the single most important test in this task: if `generateV1Sdk`
 * ever drifts from this fixture, every already-integrated v1 client site
 * (e.g. al-islah) fetching `GET /api/client/[slug]/sdk` with no `?v=` param
 * would silently receive a different `lib/cms.ts` than the one they
 * originally pasted into their repo.
 */
const EXPECTED_V1_OUTPUT = `// lib/cms.ts - generated by NE Website Manager

const CMS_BASE = 'https://cms.example.com';
const CLIENT_SLUG = 'acme';

export interface CmsPost {
  id: string;
  title: string;
  slug: string;
  content: string;
  excerpt: string;
  cover_url: string | null;
  category: string;
  tags: string[];
  status: 'published';
  seo_title: string | null;
  seo_description: string | null;
  published_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface CmsPage {
  id: string;
  title: string;
  path: string;
  content: string;
  status: 'published';
  visibility: 'public';
  updated_at: string;
}

export type AnalyticsMetadata = Record<string, string | number | boolean | null>;

async function fetchJson<T>(path: string): Promise<T> {
  const res = await fetch(\`\${CMS_BASE}\${path}\`, { next: { revalidate: 60 } });
  if (!res.ok) throw new Error(\`NE Website Manager request failed: \${res.status}\`);
  return res.json() as Promise<T>;
}

function getVisitorId() {
  if (typeof window === 'undefined') return undefined;
  const key = 'ne_visitor_id';
  let id = window.localStorage.getItem(key);
  if (!id) {
    id = crypto.randomUUID?.() ?? Math.random().toString(36).slice(2);
    window.localStorage.setItem(key, id);
  }
  return id;
}

function getSessionId() {
  if (typeof window === 'undefined') return undefined;
  const key = 'ne_session_id';
  let id = window.sessionStorage.getItem(key);
  if (!id) {
    id = crypto.randomUUID?.() ?? Math.random().toString(36).slice(2);
    window.sessionStorage.setItem(key, id);
  }
  return id;
}

export function getPosts(params?: { category?: string; limit?: number }): Promise<CmsPost[]> {
  const search = new URLSearchParams();
  if (params?.category) search.set('category', params.category);
  if (params?.limit) search.set('limit', String(params.limit));
  const qs = search.toString();
  return fetchJson<CmsPost[]>(\`/api/client/\${CLIENT_SLUG}/posts\${qs ? \`?\${qs}\` : ''}\`);
}

export function getPostBySlug(slug: string): Promise<CmsPost | null> {
  return fetchJson<CmsPost>(\`/api/client/\${CLIENT_SLUG}/posts/\${encodeURIComponent(slug)}\`)
    .catch(() => null);
}

export function getPages(): Promise<CmsPage[]> {
  return fetchJson<CmsPage[]>(\`/api/client/\${CLIENT_SLUG}/pages\`);
}

export function trackEvent(eventName: string, metadata: AnalyticsMetadata = {}) {
  if (typeof window === 'undefined') return Promise.resolve();

  const payload = {
    event_name: eventName,
    path: window.location.pathname,
    title: document.title,
    referrer: document.referrer,
    visitor_id: getVisitorId(),
    session_id: getSessionId(),
    metadata,
  };

  return fetch(\`\${CMS_BASE}/api/client/\${CLIENT_SLUG}/analytics\`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    keepalive: true,
    body: JSON.stringify(payload),
  }).then(() => undefined).catch(() => undefined);
}

export function trackPageView(metadata: AnalyticsMetadata = {}) {
  return trackEvent('page_view', metadata);
}

export function installAnalytics() {
  if (typeof window === 'undefined') return;
  trackPageView();

  const originalPushState = history.pushState;
  const originalReplaceState = history.replaceState;
  const emit = () => window.setTimeout(() => trackPageView(), 0);

  history.pushState = function pushState(...args) {
    originalPushState.apply(this, args);
    emit();
  };
  history.replaceState = function replaceState(...args) {
    originalReplaceState.apply(this, args);
    emit();
  };
  window.addEventListener('popstate', emit);
}
`;

describe('generateV1Sdk — byte-identical regression', () => {
  it('matches the historical sdk/route.ts#cmsLib output character-for-character', () => {
    const actual = generateV1Sdk(TEST_SLUG, TEST_ORIGIN);
    expect(actual).toBe(EXPECTED_V1_OUTPUT);
  });

  it('matches for a different slug/origin pair too (interpolation, not a hardcoded string)', () => {
    const actual = generateV1Sdk('other-client', 'https://manager.example.org');
    expect(actual).toContain(`const CMS_BASE = 'https://manager.example.org';`);
    expect(actual).toContain(`const CLIENT_SLUG = 'other-client';`);
    // Everything else about the shape is unchanged.
    expect(actual).toContain('export interface CmsPost {');
    expect(actual).toContain(`status: 'published';`);
  });
});

describe('generateV2Sdk — contains v1 output unchanged', () => {
  it('embeds the exact v1 output as a substring', () => {
    const v1 = generateV1Sdk(TEST_SLUG, TEST_ORIGIN);
    const v2 = generateV2Sdk(TEST_SLUG, TEST_ORIGIN, []);
    expect(v2).toContain(v1);
  });

  it('v1-only exports (getPosts, getPostBySlug, getPages, trackEvent) still present in v2', () => {
    const v2 = generateV2Sdk(TEST_SLUG, TEST_ORIGIN, []);
    expect(v2).toContain('export function getPosts(');
    expect(v2).toContain('export function getPostBySlug(');
    expect(v2).toContain('export function getPages(');
    expect(v2).toContain('export function trackEvent(');
  });
});

describe('generateV2Sdk — core v2 additions', () => {
  const v2 = generateV2Sdk(TEST_SLUG, TEST_ORIGIN, []);

  it('includes getGlobals, getNavigation, getAnnouncement, thin over CmsGlobals', () => {
    expect(v2).toContain('export function getGlobals(): Promise<CmsGlobals>');
    expect(v2).toContain('export async function getNavigation(): Promise<CmsMenuItem[]>');
    expect(v2).toContain('export async function getAnnouncement(): Promise<CmsAnnouncement | null>');
    // Thin wrappers, not re-fetches: both call getGlobals() rather than a
    // separate fetchJson to a different endpoint.
    expect(v2).toMatch(/getNavigation[\s\S]*?const globals = await getGlobals\(\);/);
    expect(v2).toMatch(/getAnnouncement[\s\S]*?const globals = await getGlobals\(\);/);
  });

  it('includes submitForm posting to the forms endpoint', () => {
    expect(v2).toContain('export async function submitForm(');
    expect(v2).toContain('/api/client/${CLIENT_SLUG}/forms/${encodeURIComponent(formSlug)}');
    expect(v2).toContain(`method: 'POST'`);
  });

  it('includes getRedirects reading {redirects} off the seo endpoint, plus the proxy snippet constant', () => {
    expect(v2).toContain('export async function getRedirects(): Promise<CmsRedirect[]>');
    expect(v2).toContain('/api/client/${CLIENT_SLUG}/seo');
    expect(v2).toContain('export const PROXY_MIDDLEWARE_SNIPPET');
    expect(v2).toContain('getRedirects');
  });

  it('lightweight syntactic sanity check: braces balance across the whole generated file', () => {
    // A real unbalanced-brace bug would show up here without needing a full
    // TS parse.
    const openBraces = (v2.match(/{/g) ?? []).length;
    const closeBraces = (v2.match(/}/g) ?? []).length;
    expect(openBraces).toBe(closeBraces);
  });
});

describe('generateV2Sdk — middleware-safe: no Edge-incompatible imports (Finding 1 regression guard)', () => {
  // `lib/cms.ts` (generateV2Sdk's output) is documented (PROXY_MIDDLEWARE_SNIPPET)
  // as safe to `import` from a client repo's own `middleware.ts`. Next.js
  // Middleware runs in the Edge Runtime by default on most Next.js versions
  // client repos actually run, which does not support Node.js APIs or
  // App-Router server-only APIs. If any of these ever leak back into this
  // file's output (e.g. a future edit accidentally moves a handler back into
  // buildV2Core), a client following the generator's own middleware snippet
  // would hit a build failure the moment they imported anything from it. This
  // test is cheap insurance against that regression.
  const v2 = generateV2Sdk(TEST_SLUG, TEST_ORIGIN, [
    { slug: 'sermons', name: 'Sermons', name_singular: 'Sermon', fields: [] },
  ]);

  it('does not import from crypto / node:crypto', () => {
    expect(v2).not.toMatch(/from ['"]crypto['"]/);
    expect(v2).not.toMatch(/from ['"]node:crypto['"]/);
    expect(v2).not.toContain('createHmac');
    expect(v2).not.toContain('timingSafeEqual');
  });

  it('does not import from next/headers', () => {
    expect(v2).not.toMatch(/from ['"]next\/headers['"]/);
    expect(v2).not.toContain('draftMode');
  });

  it('does not import from next/navigation', () => {
    expect(v2).not.toMatch(/from ['"]next\/navigation['"]/);
    // `redirect(entity.path)` is specific enough not to collide with any
    // legitimate v2-core string (no `redirect(` call exists in the
    // middleware-safe surface).
    expect(v2).not.toContain('redirect(entity.path)');
  });

  it('does not import from next/cache (handler-only: revalidatePath/revalidateTag)', () => {
    expect(v2).not.toMatch(/from ['"]next\/cache['"]/);
    expect(v2).not.toContain('revalidatePath(');
    expect(v2).not.toContain('revalidateTag(');
  });

  it('does not contain createPreviewHandler/createRevalidateHandler at all — they live in lib/cms-server.ts', () => {
    expect(v2).not.toContain('createPreviewHandler');
    expect(v2).not.toContain('createRevalidateHandler');
    expect(v2).not.toContain('CmsPreviewEntity');
  });
});

describe('generateV2ServerSdk — lib/cms-server.ts (server/Node-only companion file)', () => {
  const serverSdk = generateV2ServerSdk(TEST_SLUG, TEST_ORIGIN);

  it('leads with a comment warning not to import this file from middleware.ts', () => {
    expect(serverSdk).toContain('// lib/cms-server.ts - generated by NE Website Manager');
    expect(serverSdk).toMatch(/Do NOT import this file from\s*\n?\/\/ middleware\.ts/);
  });

  it('declares its own local CMS_BASE/CLIENT_SLUG consts (self-contained, no import from ./cms)', () => {
    expect(serverSdk).toContain(`const CMS_BASE = '${TEST_ORIGIN}';`);
    expect(serverSdk).toContain(`const CLIENT_SLUG = '${TEST_SLUG}';`);
    expect(serverSdk).not.toMatch(/from ['"]\.\/cms['"]/);
  });

  it('includes createPreviewHandler and createRevalidateHandler, syntactically plausible', () => {
    expect(serverSdk).toContain('export function createPreviewHandler(secret: string)');
    expect(serverSdk).toContain('export function createRevalidateHandler(secret: string)');

    // createPreviewHandler calls back to the CMS preview-resolution
    // endpoint with the shared secret as a header, then enables draft mode
    // and redirects to the resolved entity's path.
    expect(serverSdk).toContain('/api/client/${CLIENT_SLUG}/preview?token=');
    expect(serverSdk).toContain(`'x-ne-preview-secret': secret`);
    expect(serverSdk).toContain('draftMode()');
    expect(serverSdk).toContain('redirect(entity.path)');

    // createRevalidateHandler verifies x-ne-signature via HMAC-SHA256 and
    // calls revalidatePath/revalidateTag.
    expect(serverSdk).toContain(`req.headers.get('x-ne-signature')`);
    expect(serverSdk).toContain(`createHmac('sha256', secret)`);
    expect(serverSdk).toContain('timingSafeEqual(');
    expect(serverSdk).toContain('revalidatePath(');
    expect(serverSdk).toContain('revalidateTag(');

    // Lightweight syntactic sanity check: braces balance across the whole
    // generated file.
    const openBraces = (serverSdk.match(/{/g) ?? []).length;
    const closeBraces = (serverSdk.match(/}/g) ?? []).length;
    expect(openBraces).toBe(closeBraces);
  });

  it('leads with its Node/App-Router-only imports (crypto, next/cache, next/headers, next/navigation)', () => {
    expect(serverSdk).toContain(`import { createHmac, timingSafeEqual } from 'crypto';`);
    expect(serverSdk).toContain(`import { revalidatePath, revalidateTag } from 'next/cache';`);
    expect(serverSdk).toContain(`import { draftMode } from 'next/headers';`);
    expect(serverSdk).toContain(`import { redirect } from 'next/navigation';`);
    // Imports must lead the file (ES module convention) — before the
    // CMS_BASE/CLIENT_SLUG consts and the handler functions.
    expect(serverSdk.indexOf(`import { createHmac`)).toBeLessThan(serverSdk.indexOf('const CMS_BASE'));
  });

  it('does not duplicate any v1/v2-core export (posts/pages/collections/globals live only in lib/cms.ts)', () => {
    expect(serverSdk).not.toContain('export function getPosts(');
    expect(serverSdk).not.toContain('export function getCollection<');
    expect(serverSdk).not.toContain('export function getGlobals(');
  });
});

describe('generateV2Sdk — per-collection typed helpers', () => {
  const FIELDS: FieldDef[] = [
    { key: 'title', label: 'Title', type: 'text', required: true },
    { key: 'body', label: 'Body', type: 'richtext' },
    { key: 'views', label: 'Views', type: 'number' },
    { key: 'featured', label: 'Featured', type: 'boolean' },
    { key: 'tags', label: 'Tags', type: 'multiselect', options: ['a', 'b'] },
    { key: 'cover', label: 'Cover', type: 'image' },
    { key: 'gallery', label: 'Gallery', type: 'gallery' },
    { key: 'extra', label: 'Extra', type: 'json' },
  ];

  const collections: SdkCollectionInput[] = [
    { slug: 'sermons', name: 'Sermons', name_singular: 'Sermon', fields: FIELDS },
  ];

  const v2 = generateV2Sdk(TEST_SLUG, TEST_ORIGIN, collections);

  it('generates a Fields interface with each FieldType mapped to the documented TS type', () => {
    expect(v2).toContain('export interface SermonsFields {');
    expect(v2).toContain('title: string;'); // required text -> no `?`
    expect(v2).toContain('body?: { json: Record<string, unknown> | null; html: string };');
    expect(v2).toContain('views?: number;');
    expect(v2).toContain('featured?: boolean;');
    expect(v2).toContain('tags?: string[];');
    expect(v2).toContain('cover?: { url: string; alt: string | null };');
    expect(v2).toContain('gallery?: Array<{ url: string; alt: string | null }>;');
    expect(v2).toContain('extra?: unknown;');
  });

  it('a non-required field is optional (`key?:`); a required field is not (`key:`)', () => {
    // `title` is required -> must NOT have a `?` before its colon.
    expect(v2).toMatch(/\n {2}title: string;/);
    expect(v2).not.toMatch(/\n {2}title\?: string;/);
    // `views` is not required -> must have a `?`.
    expect(v2).toMatch(/\n {2}views\?: number;/);
  });

  it('generates get<Pascal> and get<Pascal>Entry helpers backed by the generic getCollection/getEntry', () => {
    expect(v2).toContain('export function getSermons(params?: CmsCollectionParams): Promise<CmsCollectionItem<SermonsFields>[]> {');
    expect(v2).toContain(`return getCollection<SermonsFields>('sermons', params);`);
    expect(v2).toContain('export function getSermonsEntry(itemSlug: string): Promise<CmsCollectionItem<SermonsFields> | null> {');
    expect(v2).toContain(`return getEntry<SermonsFields>('sermons', itemSlug);`);
  });

  it('supports multiple collections in one generated file, each with its own section', () => {
    const multi = generateV2Sdk(TEST_SLUG, TEST_ORIGIN, [
      { slug: 'sermons', name: 'Sermons', name_singular: 'Sermon', fields: [] },
      { slug: 'staff-members', name: 'Staff Members', name_singular: 'Staff Member', fields: [] },
    ]);
    expect(multi).toContain('export interface SermonsFields');
    expect(multi).toContain('export interface StaffMembersFields');
    expect(multi).toContain('export function getSermons(');
    expect(multi).toContain('export function getStaffMembers(');
    expect(multi).toContain('export function getStaffMembersEntry(');
  });

  it('an empty collections array generates zero collection sections but keeps the core v2 API intact', () => {
    const empty = generateV2Sdk(TEST_SLUG, TEST_ORIGIN, []);
    expect(empty).not.toContain('Fields {');
    expect(empty).toContain('export function getCollection<');
    expect(empty).toContain('export function getEntry<');
  });
});

describe('toPascalCase — collection-name-to-function-name convention', () => {
  it.each([
    ['sermons', 'Sermons'],
    ['staff-members', 'StaffMembers'],
    ['faq', 'Faq'],
    ['some-slug_like-THIS', 'SomeSlugLikeThis'],
    ['upcoming_events', 'UpcomingEvents'],
    ['a', 'A'],
    ['already-Pascal-Case', 'AlreadyPascalCase'],
  ])('%s -> %s', (input, expected) => {
    expect(toPascalCase(input)).toBe(expected);
  });

  it('is deterministic and does NOT attempt English singularization for get<Pascal>Entry', () => {
    // 'faq' famously has no clean singular/plural distinction — the naming
    // convention documented in generate.ts sidesteps this entirely by
    // suffixing `Entry` onto the SAME pascal-cased slug, rather than trying
    // to singularize. Confirm the single-item helper name is exactly
    // `getFaqEntry`, not some guessed singular like `getFaqy`/`getFa`.
    const v2 = generateV2Sdk(TEST_SLUG, TEST_ORIGIN, [
      { slug: 'faq', name: 'FAQs', name_singular: 'FAQ', fields: [] },
    ]);
    expect(v2).toContain('export function getFaqEntry(itemSlug: string)');
  });
});
