import { NextResponse } from 'next/server';
import { createAdminClient } from '@/lib/supabase/admin';

/**
 * CMS-side half of the preview flow — `GET /api/client/[slug]/preview?token=`
 * (Task 7.2). Pairs with `createPreviewHandler` in `src/lib/sdk/generate.ts`,
 * which is the CLIENT-side half generated into a client site's own
 * `lib/cms.ts`. See that function's doc comment for the full flow narrative;
 * this file is the contract it calls back into.
 *
 * `handlePreview` (`src/app/(app)/cms/posts/[id]/page.tsx`, Task 3.3; the
 * same pattern is used by the pages and collection-entry editors) mints a
 * `preview_tokens` row (migration 006) and opens
 * `{website_url}/api/preview?token=...` — a URL on the CLIENT'S OWN site.
 * That route (generated by `createPreviewHandler`) calls back HERE, passing
 * the token plus an `x-ne-preview-secret` header, and expects back exactly
 * `{ entityType, path, data }` (`CmsPreviewEntity` in `generate.ts`) on
 * success, or any non-2xx on failure (it treats every non-OK response
 * identically as "invalid or expired preview link", so the exact status
 * code returned here is only for this endpoint's own observability, not
 * part of the contract).
 *
 * Uses the service-role admin client throughout — draft/scheduled/in-review
 * content is by definition not `status = 'published'`, so it is never
 * covered by `posts_public_read` / `pages_public_read` /
 * `collection_items_public_read`'s RLS policies (all gated on
 * `status = 'published'`), and `preview_tokens` itself grants no
 * anonymous-read policy at all (migration 006: `preview_tokens_all` is
 * scoped to `my_client_id() OR is_ne_admin()`, neither of which an anonymous
 * caller satisfies). Every visibility/scoping rule RLS would otherwise
 * enforce is therefore re-implemented explicitly below.
 *
 * ## Failure modes: uniform 404
 *
 * A missing `?token=` is the one distinct case (400 — a caller error, not a
 * trust decision). Every other failure — unknown client slug, unconfigured/
 * mismatched `x-ne-preview-secret`, unknown/expired token, a token whose
 * `client_id` doesn't match this URL's client, or a token naming an entity
 * that's since been deleted — 404s identically. This deliberately does not
 * distinguish "token not found" from "token found but for the wrong client"
 * from "token found but expired": any distinction would let a caller
 * fishing with random tokens learn which guesses were *closer* than others
 * (e.g. a distinct status for "right shape, wrong client" vs "no such
 * token") — the same reasoning already established for `preview_token`
 * handling in `collections/[collection]/[itemSlug]/route.ts` and for
 * revision access in `src/app/api/cms/revisions/route.ts`.
 *
 * ## `x-ne-preview-secret` — reusing `client_publish_config.revalidate_secret`
 *
 * Validated against the SAME secret `createRevalidateHandler` (also in
 * `generate.ts`) verifies inbound webhook signatures with, rather than a
 * second preview-only secret — see `generate.ts`'s `buildV2Core` doc comment
 * for the full rationale. The check is skipped entirely (no header required)
 * when the client has no `client_publish_config` row, or that row's
 * `revalidate_secret` is null/empty — i.e. a client who hasn't opened
 * Settings -> Publishing yet can still use preview links; the secret is an
 * additional bar once configured, not a hard prerequisite for the feature to
 * work at all. A plain `===` comparison is used (not `timingSafeEqual`):
 * unlike `createRevalidateHandler`'s HMAC-signature verification — where an
 * attacker can make unlimited off-line guesses against a value derived from
 * attacker-controlled input — this compares a short-lived header value
 * against a fixed, rate-limited-by-network-round-trip secret, so a timing
 * side channel here is a materially smaller concern; using the same primitive
 * as everywhere else this codebase does a "does this string match" check
 * (e.g. `forms/[formSlug]/route.ts`'s honeypot field) keeps this consistent
 * rather than speculative hardening.
 */

interface PreviewTokenRow {
  client_id: string;
  entity_type: string;
  entity_id: string;
  expires_at: string;
}

function notFound(message = 'Not found') {
  return new Response(message, { status: 404 });
}

/** Fetches and shapes the draft/scheduled entity named by a valid preview token. Returns null if it's since been deleted. */
async function resolveEntity(
  admin: ReturnType<typeof createAdminClient>,
  clientId: string,
  entityType: string,
  entityId: string
): Promise<{ entityType: 'post' | 'page' | 'collection_entry'; path: string; data: Record<string, unknown> } | null> {
  if (entityType === 'post') {
    const { data: post } = await admin
      .from('posts')
      .select('id, title, slug, excerpt, content, cover_url, category, tags, status, seo_title, seo_description, published_at, created_at, updated_at')
      .eq('id', entityId)
      .eq('client_id', clientId)
      .single();
    if (!post) return null;
    return { entityType: 'post', path: `/blog/${post.slug as string}`, data: post as Record<string, unknown> };
  }

  if (entityType === 'page') {
    const { data: page } = await admin
      .from('pages')
      .select('id, title, path, content, status, visibility, updated_at')
      .eq('id', entityId)
      .eq('client_id', clientId)
      .single();
    if (!page) return null;
    return { entityType: 'page', path: page.path as string, data: page as Record<string, unknown> };
  }

  if (entityType === 'collection_entry') {
    const { data: item } = await admin
      .from('collection_items')
      .select('id, slug, collection_id, data, published_at, updated_at')
      .eq('id', entityId)
      .eq('client_id', clientId)
      .single();
    if (!item) return null;

    const { data: collection } = await admin
      .from('collections')
      .select('slug')
      .eq('id', item.collection_id as string)
      .single();
    if (!collection) return null;

    return {
      entityType: 'collection_entry',
      path: `/${collection.slug as string}/${item.slug as string}`,
      data: {
        id: item.id,
        slug: item.slug,
        data: item.data,
        published_at: item.published_at,
        updated_at: item.updated_at,
      },
    };
  }

  // Unknown entity_type — shouldn't happen (only 'post'/'page'/'collection_entry'
  // are ever inserted, per every editor's own `handlePreview`), but fails
  // closed rather than throwing if `preview_tokens` ever carries something else.
  return null;
}

export async function GET(
  req: Request,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params;
  const url = new URL(req.url);
  const token = url.searchParams.get('token');
  if (!token) return new Response('Missing token', { status: 400 });

  const admin = createAdminClient();

  const { data: client } = await admin.from('clients').select('id').eq('slug', slug).single();
  if (!client) return notFound('Client not found');

  const { data: config } = await admin
    .from('client_publish_config')
    .select('revalidate_secret')
    .eq('client_id', client.id as string)
    .single();

  const requiredSecret = (config?.revalidate_secret as string | null) ?? null;
  if (requiredSecret) {
    const presentedSecret = req.headers.get('x-ne-preview-secret');
    if (presentedSecret !== requiredSecret) return notFound('Invalid or expired preview link');
  }

  const { data: previewToken } = await admin
    .from('preview_tokens')
    .select('client_id, entity_type, entity_id, expires_at')
    .eq('token', token)
    .eq('client_id', client.id as string)
    .single();

  if (!previewToken) return notFound('Invalid or expired preview link');

  const row = previewToken as PreviewTokenRow;
  if (new Date(row.expires_at) <= new Date()) return notFound('Invalid or expired preview link');

  const entity = await resolveEntity(admin, client.id as string, row.entity_type, row.entity_id);
  if (!entity) return notFound('Invalid or expired preview link');

  return NextResponse.json(entity, { headers: { 'Cache-Control': 'no-store' } });
}
