import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';

const CMS_BASE = 'https://ne-website-manager.vercel.app';

function generateCmsLib(slug: string, cmsBase: string) {
  return `// lib/cms.ts — Auto-generated by NE Website Manager
// DO NOT EDIT MANUALLY — regenerate from the CMS settings panel

const CMS_BASE = '${cmsBase}';
const CLIENT_SLUG = '${slug}';

export interface CmsPost {
  id: string;
  title: string;
  slug: string;
  content: string;
  excerpt: string;
  cover_url: string | null;
  category: string;
  tags: string[];
  status: 'draft' | 'published' | 'archived';
  seo_title: string | null;
  seo_description: string | null;
  published_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface CmsPage {
  id: string;
  title: string;
  path: string;
  content: string;
  status: 'draft' | 'published';
  visibility: 'public' | 'private';
  updated_at: string;
}

export async function getPosts(): Promise<CmsPost[]> {
  const res = await fetch(\`\${CMS_BASE}/api/client/\${CLIENT_SLUG}/posts\`, {
    next: { revalidate: 60 },
  });
  if (!res.ok) return [];
  return res.json();
}

export async function getPostBySlug(slug: string): Promise<CmsPost | null> {
  const posts = await getPosts();
  return posts.find((p) => p.slug === slug) ?? null;
}

export async function getPages(): Promise<CmsPage[]> {
  const res = await fetch(\`\${CMS_BASE}/api/client/\${CLIENT_SLUG}/pages\`, {
    next: { revalidate: 60 },
  });
  if (!res.ok) return [];
  return res.json();
}
`;
}

async function githubRequest(
  token: string,
  method: string,
  path: string,
  body?: object
) {
  const res = await fetch(`https://api.github.com${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const json = await res.json();
  if (!res.ok) throw new Error(json.message ?? `GitHub ${res.status}`);
  return json;
}

export async function POST(req: Request) {
  // Auth check
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const { data: profile } = await supabase
    .from('profiles')
    .select('role, client_id')
    .eq('id', user.id)
    .single();

  const { github_token, repo, slug, client_name } = await req.json();

  if (!github_token || !repo || !slug) {
    return NextResponse.json({ error: 'github_token, repo, slug required' }, { status: 400 });
  }

  // Validate caller owns this client OR is ne_admin
  if (profile?.role !== 'ne_admin') {
    const { data: clientRow } = await supabase
      .from('clients')
      .select('id')
      .eq('slug', slug)
      .single();
    if (!clientRow || clientRow.id !== profile?.client_id) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }
  }

  try {
    // 1. Get default branch
    const repoInfo = await githubRequest(github_token, 'GET', `/repos/${repo}`);
    const defaultBranch = repoInfo.default_branch ?? 'main';

    // 2. Get latest commit SHA on default branch
    const refData = await githubRequest(github_token, 'GET', `/repos/${repo}/git/ref/heads/${defaultBranch}`);
    const baseSha = refData.object.sha;

    // 3. Create new branch
    const branchName = `cms/ne-integration-${Date.now()}`;
    await githubRequest(github_token, 'POST', `/repos/${repo}/git/refs`, {
      ref: `refs/heads/${branchName}`,
      sha: baseSha,
    });

    // 4. Upsert lib/cms.ts
    const fileContent = generateCmsLib(slug, CMS_BASE);
    const encoded = Buffer.from(fileContent).toString('base64');

    // Check if file exists (to get SHA for update)
    let existingSha: string | undefined;
    try {
      const existing = await githubRequest(github_token, 'GET', `/repos/${repo}/contents/lib/cms.ts?ref=${branchName}`);
      existingSha = existing.sha;
    } catch {
      // File doesn't exist — create fresh
    }

    await githubRequest(github_token, 'PUT', `/repos/${repo}/contents/lib/cms.ts`, {
      message: `feat: add NE Website Manager CMS integration for ${client_name ?? slug}`,
      content: encoded,
      branch: branchName,
      ...(existingSha ? { sha: existingSha } : {}),
    });

    // 5. Create PR
    const pr = await githubRequest(github_token, 'POST', `/repos/${repo}/pulls`, {
      title: `Add NE Website Manager CMS integration`,
      body: `## NE Website Manager Integration\n\nThis PR adds \`lib/cms.ts\` — a typed API client that connects this website to the NE Website Manager CMS.\n\n### Usage\n\n\`\`\`ts\nimport { getPosts, getPostBySlug, getPages } from '@/lib/cms';\n\n// Fetch all published posts\nconst posts = await getPosts();\n\n// Fetch single post\nconst post = await getPostBySlug('my-post-slug');\n\`\`\`\n\n### API Endpoints\n- Posts: \`${CMS_BASE}/api/client/${slug}/posts\`\n- Pages: \`${CMS_BASE}/api/client/${slug}/pages\`\n\n---\n*Generated by [NE Website Manager](${CMS_BASE})*`,
      head: branchName,
      base: defaultBranch,
    });

    // 6. Save github_repo to client record (for display)
    await supabase.from('clients').update({ github_repo: repo }).eq('slug', slug);

    return NextResponse.json({ success: true, pr_url: pr.html_url, pr_number: pr.number });

  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Unknown error';
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
